### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'torch._C._TensorMeta'

### ISSUE THREAD

**Issue by yudongjian** [Lornatang/CycleGAN_PyTorch#12]
ｈｉ，　Ｉ　ｈｏｐｅ　ｙｏｕｒ　ｈｅｌｐ．　Ｔｈａｎｋｓ！
ｅｒｒｏｒ
python3 train.py --config_path ./configs/CYCLEGAN.yaml

```
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    from dataset import CUDAPrefetcher, ImageDataset
  File "/home/image1325_user/ssd_disk2/yudongjian_23/CycleGAN-PyTorch-master/dataset.py", line 25, in <module>
    from imgproc import image_to_tensor
  File "/home/image1325_user/ssd_disk2/yudongjian_23/CycleGAN-PyTorch-master/imgproc.py", line 105, in <module>
    src_images: ndarray | Tensor | list[ndarray] | list[Tensor],
TypeError: unsupported operand type(s) for |: 'type' and 'torch._C._TensorMeta'
```

**Comment by Lornatang** [comment]
Use Python==3.10.x
