### ISSUE TITLE
RuntimeError: Tried to instantiate dummy base class Stream

### ISSUE THREAD

**Issue by wuwuaaa** [Lornatang/CycleGAN_PyTorch#14]
Traceback (most recent call last):
  File "E:\lunwen\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\train.py", line 545, in <module>
    main()
  File "E:\lunwen\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\train.py", line 54, in main
    train_prefetcher = load_dataset(config.src_image_path,
  File "E:\lunwen\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\train.py", line 240, in load_dataset
    train_prefetcher = CUDAPrefetcher(train_dataloader, device)
  File "E:\lunwen\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\CycleGAN-PyTorch-88e1f17a8a7be24b982cce16a6cf0db043e13bdc\dataset.py", line 172, in __init__
    self.stream = torch.cuda.Stream()
  File "F:\anaconda\envs\cycle\lib\site-packages\torch\cuda\streams.py", line 34, in __new__
    return super().__new__(cls, priority=priority, **kwargs)
  File "F:\anaconda\envs\cycle\lib\site-packages\torch\cuda\_utils.py", line 49, in err_fn
    raise RuntimeError(f"Tried to instantiate dummy base class {class_name}")
May I ask what the reason is? Is it because I can't find CUDA on my computer? If I only use CPU training, how should I modify the code

**Comment by wuwuaaa** [comment]
the last sentence"RuntimeError: Tried to instantiate dummy base class Stream"
